// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for windows - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTsMwlmeObS8mbnmt59VcwrpZrSnnA8DA',
    appId: '1:529630118134:web:c4b52224d5a0135aa0acd7',
    messagingSenderId: '529630118134',
    projectId: 'niransnarayanan-web',
    authDomain: 'niransnarayanan-web.firebaseapp.com',
    storageBucket: 'niransnarayanan-web.appspot.com',
    measurementId: 'G-68514SSD96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAWkL1QVaPB5QV_K0ke5MjwltvBMnj9yU',
    appId: '1:529630118134:android:22ff58d3bb9bddaaa0acd7',
    messagingSenderId: '529630118134',
    projectId: 'niransnarayanan-web',
    storageBucket: 'niransnarayanan-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBniAQuePEojBsXtwRe2fP2MVBWIb5X-uY',
    appId: '1:529630118134:ios:39c63be7e8f9be1ca0acd7',
    messagingSenderId: '529630118134',
    projectId: 'niransnarayanan-web',
    storageBucket: 'niransnarayanan-web.appspot.com',
    iosClientId:
        '529630118134-80slv7607vgcdgv6q4mou7aeggbjoa2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.niransnarayanan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBniAQuePEojBsXtwRe2fP2MVBWIb5X-uY',
    appId: '1:529630118134:ios:39c63be7e8f9be1ca0acd7',
    messagingSenderId: '529630118134',
    projectId: 'niransnarayanan-web',
    storageBucket: 'niransnarayanan-web.appspot.com',
    iosClientId:
        '529630118134-80slv7607vgcdgv6q4mou7aeggbjoa2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.niransnarayanan',
  );
}
