name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # Triggers the workflow only when pushing to the main branch
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can adjust the Node.js version if needed

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd web  # Adjust if your website folder has a different name
          firebase deploy --only hosting
