name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # Triggers the workflow only when pushing to the main branch
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure this matches the environment requirements

      - name: Display Node.js version
        run: node -v  # Check the actual Node.js version being used

      - name: Display npm version
        run: npm -v  # Check the npm version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build web

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd web  # Ensure this matches your folder structure
          firebase deploy --only hosting
